name: Tyger

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request: # all branches
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_CLIENT_ID: 789b8572-1fae-4a5f-b376-6d9d14651245
  AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
  AZURE_SUBSCRIPTION_ID: 87d8acb3-5176-4651-b457-6ab9cefd8e3d

  CAN_ACCESS_SECRETS: ${{ secrets.CAN_ACCESS_SECRETS }}

jobs:

  codeql:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'go' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        if: matrix.language == 'go'
        with:
          go-version-file: cli/go.mod
          cache-dependency-path: cli/go.sum

      - uses: actions/setup-dotnet@v3
        if: matrix.language == 'csharp'
        with:
          global-json-file: server/global.json

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: manual

      - name: "Build"
        run: |
          set -euo pipefail
          make -s build-${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
